# configures the nodes into a Windows Failover Cluster
---
# this command requires the credentials of a domain user 
- name: Configure Windows Failover Clustering
  win_command: powershell.exe -
  args:
    stdin: "$pass = ConvertTo-SecureString {{ domain_join_admin_password }} -AsPlainText -Force; $creds = New-Object System.Management.Automation.PSCredential({{ domain_join_admin_user }}, $pass); $session = New-PSSession localhost -Credential $creds; Invoke-Command -Session $session -ScriptBlock {New-Cluster -Name {{ cluster_name }} -Node {{ node_array }} -AdministrativeAccessPoint ActiveDirectoryAndDns}"

- name: Reboot to Windows Failover Clustering configuration.
  win_reboot:
    post_reboot_delay: 60
