# enable remote desktop access
---
- name: Allow Remote Desktop Services (RDP) through firewall - TCP 3389
  win_firewall_rule:
    name: Remote Desktop
    localport: 3389
    action: allow
    direction: in
    protocol: tcp
    profiles: domain,private,public
    state: present
    enabled: yes

    
- name: Allow users to connect remotely by using Remote Desktop Services (RDP)
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services
    name: fDenyTSConnections
    data: 00000000
    type: dword
    state: "present"
  register: register_remote_desktop_enabled
  tags:
    - configuration

# https://getadmx.com/?Category=Windows_10_2016&Policy=Microsoft.Policies.TerminalServer::TS_SECURITY_LAYER_POLICY
- name: Require use of specific security layer for remote (RDP) connections
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services
    name: SecurityLayer
    data: "1"
    type: dword
    state: "present"
  tags:
    - configuration

# https://getadmx.com/?Category=Windows_10_2016&Policy=Microsoft.Policies.TerminalServer::TS_ENCRYPTION_POLICY
- name: Set remote (RDP) client connection encryption level
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services
    name: MinEncryptionLevel
    data: "3"
    type: dword
    state: "present"
  tags:
    - configuration